apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    component: elasticsearch
    group: logging
spec:
  type: NodePort
  selector:
    component: elasticsearch
    group: logging
  ports:
    - name: http
      port: 9200
      targetPort: 9200
