---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
  namespace: kiali-operator
  labels:
    app: kiali-operator
    version: v1.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-operator
      version: v1.1.0
  template:
    metadata:
      name: kiali-operator
      labels:
        app: kiali-operator
        version: v1.1.0
    spec:
      serviceAccountName: kiali-operator
      containers:
      - name: ansible
        command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: quay.io/kiali/kiali-operator:v1.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - name: operator
        image: quay.io/kiali/kiali-operator:v1.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          value: kiali-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kiali-operator"
      volumes:
      - name: runner
        emptyDir: {}
