apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: pg-minimal-cluster
  namespace: postgres
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-11:1.5-p9
  teamId: "PG"
  volume:
    size: 3Gi
  numberOfInstances: 2
  users:
    # database owner
    bygui:
      - superuser
      - createdb
    # role for application foo
    # foo_user: []
  databases:
    # dbname: owner
    server-app: bygui
  postgresql:
    version: "10"
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  resources:
    requests:
      cpu: 250m
      memory: 256M
    limits:
      cpu: 500m
      memory: 512M
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"