apiVersion: v1
kind: Service
metadata:
  name: pg-minimal-cluster
  labels:
    application: spilo
    version: pg-minimal-cluster
    spilo-role: master
spec:
  selector:
    application: spilo
    version: pg-minimal-cluster
    # spilo-role: master
  ports:
    - name: tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: tcp-2
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: tcp-3
      port: 8008
      protocol: TCP
      targetPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: pg-minimal-cluster-repl
  labels:
    application: spilo
    version: pg-minimal-cluster
    spilo-role: replica
spec:
  selector:
    application: spilo
    version: pg-minimal-cluster
    # spilo-role: replica
  ports:
    - name: tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: tcp-2
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: tcp-3
      port: 8008
      protocol: TCP
      targetPort: 8008
