apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: log-server
spec:
  hosts:
    - log-server
  http:
  - route:
    - destination:
        host: log-server
        subset: v2
      weight: 100