
FROM golang:1.12-stretch AS gobuilder

WORKDIR /go/src/github.com/bygui86/kubernetes-tests/applications/client-app-go
COPY . .

RUN ["/bin/bash", "-c", "go get -v -d ."]
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /bin/app .

# ---

FROM alpine

RUN apk add --no-cache bash

WORKDIR /bin/
COPY --from=gobuilder /bin/app .

EXPOSE 8080
EXPOSE 8090

ENTRYPOINT "/bin/app"
