apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    component: fluentd
    group: logging
    # version: v1.3
    version: 2.5.1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      component: fluentd
      group: logging
      # version: v1.3
      version: 2.5.1
  template:
    metadata:
      labels:
        component: fluentd
        group: logging
        # version: v1.3
        version: 2.5.1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: fluentd
          # image: fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch
          image: gcr.io/fluentd-elasticsearch/fluentd:v2.5.1
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.logging"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENT_UID
              value: "0"
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
