apiVersion: v1
kind: Service
metadata:
  name: server-app
  namespace: default
  labels:
    app: server-app
    group: sample
spec:
  type: NodePort
  selector:
    app: server-app
    group: sample
  ports:
    - name: comm
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
