apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-app-go
  namespace: default
  labels:
    app: client-app-go
    group: sample
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-app-go
  targetCPUUtilizationPercentage: 75
