apiVersion: v1
kind: Service
metadata:
  name: log-server
  labels:
    app: log-server
    group: istio-mirroring
spec:
  type: NodePort
  selector:
    app: log-server
    # group: istio-mirroring
  ports:
    - name: http
      port: 7001
      targetPort: 7001
      # protocol: TCP
    - name: http-metrics
      port: 7090
      targetPort: 7090
      # protocol: TCP
