apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: demo
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: ./example.rules
      rules:
        - alert: ExampleAlert
          expr: vector(1)
          for: 10s
          labels:
            severity: warning
          annotations:
            description: Demo Example Alert description
            summary: Demo Example Alert summary
