apiVersion: v1
kind: Service
metadata:
  name: sleepybox
  labels:
    app: sleepybox
    group: sample
spec:
  type: ClusterIP
  selector:
    app: sleepybox
    group: sample
  ports:
    - name: tcp
      port: 8600
      targetPort: 8600
      protocol: TCP
