apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cassandra
  labels:
    app: cassandra
    group: db
    # prometheus: observability
    # prometheus: kube-prometheus
    release: mon
spec:
  selector:
    matchLabels:
      app: cassandra
      group: db
    # namespaceSelector:
    #   matchNames:
    #     - default
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 59s
