global:
  resolve_timeout: 5m
  slack_api_url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
route:
  group_by:
    - job
  group_interval: 5m
  group_wait: 30s
  repeat_interval: 30s
  receiver: slack
receivers:
  - name: slack
    slack_configs:
      - channel: "#demo-alerts"
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        send_resolved: true
        link_names: true
