apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    component: kibana
    group: logging
spec:
  type: NodePort
  selector:
    component: kibana
    group: logging
  ports:
    - name: http
      port: 5601
      targetPort: 5601
