apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  storageClassName: ssd-expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
