apiVersion: v1
kind: Secret
metadata:
  name: server-app-mysql
  labels:
    app: server-app-mysql
    group: sample
type: Opaque
data:
#  user
  MYSQL_USERNAME: "dXNlcg=="
  MYSQL_PASSWORD: "c2VjcmV0"
#  root
#  MYSQL_USERNAME: "cm9vdA=="
#  MYSQL_PASSWORD: "cm9vdHNlY3JldA=="
