apiVersion: apps/v1
kind: Deployment
metadata:
  name: spekt8
  namespace: tools
  labels:
    app: spekt8
    group: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spekt8
      group: tools
  template:
    metadata:
      labels:
        app: spekt8
        group: tools
    spec:
      containers:
        - name: spekt8
          image: elliotxkim/spekt8
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 512M
            limits:
              cpu: 500m
              memory: 512M
