apiVersion: v1
kind: Service
metadata:
  name: server-app-postgres
  labels:
    app: server-app-postgres
    group: sample
spec:
  type: NodePort
  selector:
    app: server-app-postgres
    group: sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
