apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-client
  labels:
    app: gemini-client
    group: sample
    version: 0.0.1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: gemini-client
      group: sample
      version: 0.0.1
  template:
    metadata:
      labels:
        app: gemini-client
        group: sample
        version: 0.0.1
    spec:
      restartPolicy: Always
      containers:
        - name: client-app-go
          image: client-app-go:latest
          # Kubernetes
          # imagePullPolicy: Always
          # Minikube
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: client-app-go
          ports:
            - name: http-app
              containerPort: 8080
            - name: http-app-mtr
              containerPort: 8090
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /live
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
        - name: echo-client
          image: echo-client:latest
          # Kubernetes
          # imagePullPolicy: Always
          # Minikube
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: echo-client
          ports:
            - name: http-echo
              containerPort: 7001
            - name: http-echo-mtr
              containerPort: 7090
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /live
              port: 7090
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 7090
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      terminationGracePeriodSeconds: 30
