apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-app-h2
  namespace: default
  labels:
    app: server-app-h2
    group: sample
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-app-h2
  targetCPUUtilizationPercentage: 75
