apiVersion: v1
kind: Service
metadata:
  name: echo-client
  namespace: default
  labels:
    app: echo-client
    group: sample
spec:
  type: NodePort
  selector:
    app: echo-client
    group: sample
  ports:
    - name: http
      port: 7001
      targetPort: 7001
      protocol: TCP
    - name: http-metrics
      port: 7090
      targetPort: 7090
      protocol: TCP
