apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf-external
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    #Config to redirect http to https
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

    [[tls]]
      entryPoints = ["https"]
      [tls.certificate]
        certFile = "/certs/cert.crt"
        keyFile = "/certs/cert.key"
      [tls.defaultCertificate]
        certFile = "/certs/cert.crt"
        keyFile = "/certs/cert.key"

    [api]
      [api.statistics]
        recentErrors = 10

    [kubernetes]
      # Only create ingresses where the object has traffic-type: external label
      labelselector = "traffic-type=external"

    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"

    [ping]
      entryPoint = "http"

    [accessLog]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-ssl-certificates
  namespace: kube-system
data:
  cert.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lVREF1b2htUUhVb2lGb2JsSzdHL3Jqc0tOdmtNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dqRVlNQllHQTFVRUF3d1BLaTUwY21GbFptbHJMbXh2WTJGc01CNFhEVEU1TURVd09EQTVNVGN5TmxvWApEVEl3TURVd056QTVNVGN5Tmxvd0dqRVlNQllHQTFVRUF3d1BLaTUwY21GbFptbHJMbXh2WTJGc01JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXY2Sjk2MFY3S0dTa0tRUGhsYkQyVFRJbXJ6RXcKU3plUXdMNEs2bGpiWnhDa3BaZ251L1hFZDBLbVZRbHFqUHZScWZCbGtqMFlTaHU4eksxYVRMNm1PeWg2U3BTYQpBT3g0S25kQnhTSFlsL2FNd2NJOXhNV2p4STY5Z2VOeHNKeDNlaHVpcHBVRDgrZUwxYzRMRE1kRGk3enNrajYyCi8wYnN1R0E5cldKUEVKQnZ2czhNazluNTg4bnMwT3phei9EUS9VUks3MVdnWDZKQVFxTmdnclZ2Q1BieWRTOUoKRExmT1ptZjZhYW9nRjJVZTdjTnl6cG9UbXBSSE5ERVNDcWFwZkgxVmNUSXpyb3VIODNGMDdxTytDS0lwTVkyRQpRdG05TEU0bno3aHVTQktwVVhuSW9UNXpvejg1L042T1RVZFlUeC9rVTl2cEZicVBEb3UvSzdDTnhRSURBUUFCCm8xTXdVVEFkQmdOVkhRNEVGZ1FVazdBZGhwOGExd1ZiWWNLODBxQmlMbFZQRm5Zd0h3WURWUjBqQkJnd0ZvQVUKazdBZGhwOGExd1ZiWWNLODBxQmlMbFZQRm5Zd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFkb04wOE04aHJFcTNuM3lBYldhZUUvZjlieXRWWlpkeVFCaEZPNVZmVHMyQXhhNFVNdkI5CnpDZjNHdE1LWlZRdDIyc0VvRTQzTU9QY1czbmZiQnFyYkxYYUx2VVVqNXlsRFAyNjZqWmtQRVVFaEh5eW15VDUKci92c2MyVzdUTzhRMytMLzNLL3RWRTNLSmZpcVFiT2ZoZUttclpkSWhCaEp6a09DWlBCSnR3Rk1yVGgzZ1dubApnUlpESzN6VmZxWWFqeUxnKytkdjdMWVpnL2ppOUtZdDZPRVZaN3BaMjFyUG5Ecnc2ejRUaC9Yb1RYSFlSNkkvClpFRVRzQVM5UklBWGpqTUVyM2g0Q3RjZEhlbzNIbE82a0hidG9jd0wwSHBnczU0VEp1NFphWkZDZ0s2cE56R0YKQkF2cDZKdVVzS0JzMHlIb1Foa2F0ZVB5NndLVndlcER0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  cert.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQy9vbjNyUlhzb1pLUXAKQStHVnNQWk5NaWF2TVRCTE41REF2Z3JxV050bkVLU2xtQ2U3OWNSM1FxWlZDV3FNKzlHcDhHV1NQUmhLRzd6TQpyVnBNdnFZN0tIcEtsSm9BN0hncWQwSEZJZGlYOW96QndqM0V4YVBFanIyQjQzR3duSGQ2RzZLbWxRUHo1NHZWCnpnc014ME9Mdk95U1ByYi9SdXk0WUQydFlrOFFrRysrend5VDJmbnp5ZXpRN05yUDhORDlSRXJ2VmFCZm9rQkMKbzJDQ3RXOEk5dkoxTDBrTXQ4NW1aL3BwcWlBWFpSN3R3M0xPbWhPYWxFYzBNUklLcHFsOGZWVnhNak91aTRmegpjWFR1bzc0SW9pa3hqWVJDMmIwc1RpZlB1RzVJRXFsUmVjaWhQbk9qUHpuODNvNU5SMWhQSCtSVDIra1Z1bzhPCmk3OHJzSTNGQWdNQkFBRUNnZ0VBR2hYcllCQklNSHBxb2k2bUVYTlNRN1hVOERvWTRkUkJmd3NmZjBEek5MZGUKUWpCUkVGUG5GM2phSFc4M3N0TkFlZ3FBT1FUWi9wU0NBYmFET1RrbWRaMFA4SUVENmFaR3dUa1VtZG4rbXNqego1aGdqd2xwSTdhT2toajdJcGdyV2RLZTRYMGFma0I3dnVQM2dJVEFxc0tYWjZocGhYS1J4NnJNbkVpZjByVU5QClF5NE5tL3hzOVRBQVUzMEY4U3JPbjhMZHh0R1ZLbFlvb1BLTUE3dTl2Q29zNGJQQTYvcGMwcnRFVWV1bklDM0gKZy9TY0hMNUtOYVp1dUl2WE9KclJWazU3bE0xdnJIMTduNUwyd0UrTUoyUVlSNUNjaHY0RHZacDg4V2x1NG9tOApQMk9wZlVxdWo4ckJ6dC9TNTRCWWExRjJ4QjdWVktjbjJhVHZPMVIrUVFLQmdRRDZMb21hZ0xqWkVTU3g2NStTCkNFb3plajdNc2VqYkZJU3R1NGhpdzVvcFpBYjd1US95dm1iR21JWDJ0RWo1N0ZhRytZb3B5d3dUSFZRMFdQMVEKZHhsak5QVGxNdkY2WnlIZFZOL042WU9QN3pod0tCNktRbEh0alkxdk9qdVJuVS9CZnFOMjdXSHdCK0daOGtXUgpJYnNMODBENTgycmtQNDZWMzZXY2ZGZWJOUUtCZ1FERUYyU3NXeGxMeE0xclBDZmFGN2lISE1NcEZBalNZWnFwCkl5NEVtTTNPcEs2QmtqeDVoaWJFT0w3VTBEWWFiNnd6M21rMHhkaVZ4UEdxSk5sNzhqK25FWTl4amhYbEtHTTAKNEhCYTk0UGJtVnpnVlBjalZnOEpLdEFrMjZzTjk5bkJCY2FZMTVWWjlIVnRCNmNISGsvV1hvT2hUSkVBbXJMeQpUVVFQNlBMcVVRS0JnSDZFUmtZQnpuakhPSjFaSUtzQzBqTlNJS3YzVkdCbDhlckJxV2o0cmQ4OG5HTno1T0xHCjhzWi9uMDl4UUc1UzNEY0p2cHIvK2EwNDZicEhQbU1RdDUvNXlkYVdlcE9CMEJoVHNaSTZBclFwTDR0WVhvbGcKbkhuYldhamo4L2ZoYTlIWUx1WVhpYTJPN3NHaFNSanB5K054TW15MGNsdlc0RTVlZVN1M25iMzVBb0dBRWNkbApNMU5YS2MyQUtuYmJ6aVJVY0x1azNqYVl6aXBYVVhxRkU1bWZIMXRERHpCcEYwT1loRFg0NTJheFlSZzY3c0Q5Cm5QRkxQOWtKYURuTEZqZlNtWjAzK2oyOXNuZEU5MmhhQjRWbGlTV1FqQzVuOGVZOW1zRXMrZ3FJcWMyTkNya3gKVm01RmRsQjV6UmJpaC95eGxHZ2hXeUNNRFJmNW5ZcHYzMWxwbk9FQ2dZQk1lZ0dUaUNzV0JySDlsQkQxV2M5OQo2dTEwZ2dWbERKOGlVWndycUZteXk0c21SMHFsNEwyZ244TVduTlFDQVJyNUl5dmp4SHFzcy9GV3JXOXJ6MDFDCmE3ZDlNUXFqWFY1djAyWjNwcVF1a0Y2QWpWMmlsb1hicGZQR2Z6Y0xKRVRqNFRxcEQ4b1N1TFNaTlhiaVhRNXMKUUtPU3BwbGw3M2dEYWYxNXRYRnBJUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
