apiVersion: v1
kind: ConfigMap
metadata:
  name: server-app-postgres
  labels:
    app: server-app-postgres
    group: sample
data:
  SPRING_PROFILES_ACTIVE: "kube-cluster"
  HEAP_SIZE: "256m"
  META_SIZE: "300m"
  POSTGRESQL_SCHEMA: "foo"
  SERVER_TRACING_PROBABILITY: "1.0"
