apiVersion: v1
kind: Service
metadata:
  name: client-app-java
  namespace: default
  labels:
    app: client-app-java
    group: sample
spec:
  type: NodePort
  selector:
    app: client-app-java
    group: sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
