apiVersion: v1
kind: ConfigMap
metadata:
  name: server-app-mongo
  labels:
    app: server-app-mongo
    group: sample
data:
  SPRING_PROFILES_ACTIVE: "kube"
  HEAP_SIZE: "256m"
  META_SIZE: "300m"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  MONGODB_DB: "server-app"
  SERVER_TRACING_PROBABILITY: "1.0"
