---
# Source: mongodb/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-5.20.0
    release: "mongodb"
type: Opaque
data:
  mongodb-root-password:  "cm9vdHNlY3JldA=="
  mongodb-password:  "c2VjcmV0"

---
# Source: mongodb/templates/pvc-standalone.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongodb
    chart: mongodb-5.20.0
    release: mongodb
  name: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"

---
# Source: mongodb/templates/svc-standalone.yaml

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-5.20.0
    release: "mongodb"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: "mongodb"

---
# Source: mongodb/templates/deployment-standalone.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-5.20.0
    release: "mongodb"
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "mongodb"
  template:
    metadata:
      labels:
        app: mongodb
        release: "mongodb"
        chart: mongodb-5.20.0
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.0.10-debian-9-r13
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-password
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-root-password
        - name: MONGODB_USERNAME
          value: "user"
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_DATABASE
          value: "server-app"
        - name: MONGODB_ENABLE_IPV6
          value: "yes"
        - name: MONGODB_ENABLE_DIRECTORY_PER_DB
          value: "no"
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
          subPath: ""
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb
