apiVersion: v1
kind: Secret
metadata:
  name: server-app-mongo
  labels:
    app: server-app-mongo
    group: sample
type: Opaque
data:
#  user
  MONGO_USERNAME: "dXNlcg=="
  MONGO_PASSWORD: "c2VjcmV0"
#  root
#  MONGO_USERNAME: "cm9vdA=="
#  MONGO_PASSWORD: "cm9vdHNlY3JldA=="
