apiVersion: v1
kind: Service
metadata:
  name: server-app-mongo
  namespace: default
  labels:
    app: server-app-mongo
    group: sample
spec:
  type: NodePort
  selector:
    app: server-app-mongo
    group: sample
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
