apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka
  labels:
    app: kafka
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
mountOptions:
  - debug
