apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-app-java
  labels:
    app: client-app-java
    group: sample
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-app-java
  targetCPUUtilizationPercentage: 75
