apiVersion: v1
kind: Service
metadata:
  name: acid-minimal-cluster
  labels:
    application: spilo
    version: acid-minimal-cluster
    spilo-role: master
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minimal-cluster.acid.staging.db.example.com
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  type: ClusterIP
  selector:
    application: spilo
    version: acid-minimal-cluster
    # spilo-role: master
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: tcp-1
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: tcp-2
      port: 8008
      protocol: TCP
      targetPort: 8008
